services:
  qbittorrent-dev:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-dev
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    restart: unless-stopped
    networks:
      - ab-dev-network
    ports:
      - "8081:8081" # Web UI 端口
      # - "6881:6881"
      # - "6881:6881/udp"
    environment:
      # - PUID=$(id -u)
      # - PGID=$(id -g)
      - TZ=Asia/Taipei
      - WEBUI_PORT=8081
    volumes:
      - ./dev/qb_config:/config
      - ./dev/Bangumi:/downloads # 這裡改為你想要存動畫的路徑

networks:
  ab-dev-network:
    driver: bridge