"""baseline

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-17 19:33:15.828759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rssitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('aggregate', sa.Boolean(), nullable=False),
    sa.Column('parser', sa.String(), nullable=False),
    sa.Column('last_update', sa.String(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rssitem'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('bangumi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rss_id', sa.Integer(), nullable=True),
    sa.Column('official_title', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('title_raw', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_raw', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('dpi', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('eps_collect', sa.Boolean(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('filter', sa.String(), nullable=False),
    sa.Column('rss_link', sa.String(), nullable=False),
    sa.Column('poster_link', sa.String(), nullable=True),
    sa.Column('added', sa.Boolean(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('save_path', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('pending_review', sa.Boolean(), nullable=False),
    sa.Column('global_filter_matches', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['rss_id'], ['rssitem.id'], name=op.f('fk_bangumi_rss_id_rssitem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bangumi')),
    sa.UniqueConstraint('official_title', 'season', 'group_name', name='uq_bangumi_title_season_group')
    )
    op.create_table('torrent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=True),
    sa.Column('rss_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'queued', 'downloading', 'completed', 'renaming', 'renamed', 'error', 'stale', 'missing', 'excluded', name='torrentstate'), server_default='pending', nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('renamed_at', sa.DateTime(), nullable=True),
    sa.Column('renamed_file_count', sa.Integer(), nullable=True),
    sa.Column('pikpak_cloud_path', sa.String(), nullable=True),
    sa.Column('pikpak_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], name=op.f('fk_torrent_bangumi_id_bangumi')),
    sa.ForeignKeyConstraint(['rss_id'], ['rssitem.id'], name=op.f('fk_torrent_rss_id_rssitem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_torrent')),
    sa.UniqueConstraint('hash', 'bangumi_id', name='uq_torrent_hash_bangumi')
    )
    # Partial unique index on torrent(hash, bangumi_id) where hash IS NOT NULL.
    # Preserved from legacy _run_migrations() to keep parity with prod DBs.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_torrent_hash_bangumi "
        "ON torrent (hash, bangumi_id) WHERE hash IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_torrent_hash_bangumi")
    op.drop_table('torrent')
    op.drop_table('bangumi')
    op.drop_table('user')
    op.drop_table('rssitem')
    # ### end Alembic commands ###
