"""add_series

Revision ID: 0002_add_series
Revises: 0001_baseline
Create Date: 2026-04-17 20:20:15.892570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002_add_series"
down_revision: Union[str, Sequence[str], None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_bangumi_id', sa.Integer(), nullable=True),
    sa.Column('canonical_title', sa.String(), nullable=False),
    sa.Column('normalized_title', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('cour_part', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('default_filter', sa.String(), nullable=True),
    sa.Column('default_offset', sa.Integer(), nullable=False),
    sa.Column('pending_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%f', 'now'))"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('mikan_bangumi_id', name='uq_series_mikan'),
    sa.UniqueConstraint('normalized_title', 'season', 'cour_part', name='uq_series_fallback')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_normalized_title'), ['normalized_title'], unique=False)

    # Partial unique index for the NULL cour_part case.
    # SQL UNIQUE constraints treat NULLs as distinct, so two rows with
    # (normalized_title='x', season=1, cour_part=NULL) would not violate
    # uq_series_fallback. This partial index closes that gap.
    op.execute(
        "CREATE UNIQUE INDEX uq_series_fallback_null_cour "
        "ON series (normalized_title, season) WHERE cour_part IS NULL"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_series_fallback_null_cour")

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_normalized_title'))

    op.drop_table('series')
    # ### end Alembic commands ###
