"""add_mikan_ref

Revision ID: 35869690f187
Revises: 0002_add_series
Create Date: 2026-04-17 20:46:47.277204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003_add_mikan_ref"
down_revision: Union[str, Sequence[str], None] = "0002_add_series"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mikan_episode_ref',
    sa.Column('info_hash', sa.String(), nullable=False),
    sa.Column('mikan_bangumi_id', sa.Integer(), nullable=True),
    sa.Column('mikan_subgroup_id', sa.Integer(), nullable=True),
    sa.Column('canonical_title', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('info_hash', name=op.f('pk_mikan_episode_ref'))
    )
    with op.batch_alter_table('mikan_episode_ref', schema=None) as batch_op:
        batch_op.create_index('ix_mikan_episode_ref_series', ['mikan_bangumi_id', 'mikan_subgroup_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikan_episode_ref', schema=None) as batch_op:
        batch_op.drop_index('ix_mikan_episode_ref_series')

    op.drop_table('mikan_episode_ref')
    # ### end Alembic commands ###
