"""add_pending_enrichment

Revision ID: 79cb116b361b
Revises: 0003_add_mikan_ref
Create Date: 2026-04-17 20:59:13.908022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004_add_pending_enrichment"
down_revision: Union[str, Sequence[str], None] = "0003_add_mikan_ref"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_torrent_enrichment',
    sa.Column('info_hash', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('rss_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rss_id'], ['rssitem.id'], name=op.f('fk_pending_torrent_enrichment_rss_id_rssitem'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('info_hash', name=op.f('pk_pending_torrent_enrichment'))
    )
    with op.batch_alter_table('pending_torrent_enrichment', schema=None) as batch_op:
        batch_op.create_index('ix_pending_torrent_enrichment_rss', ['rss_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_torrent_enrichment', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_torrent_enrichment_rss')

    op.drop_table('pending_torrent_enrichment')
    # ### end Alembic commands ###
