"""add_merge_history

Revision ID: 0005_add_merge_history
Revises: 0004_add_pending_enrichment
Create Date: 2026-04-17 21:05:01.643682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0005_add_merge_history"
down_revision: Union[str, Sequence[str], None] = "0004_add_pending_enrichment"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangumi_merge_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=False),
    sa.Column('merged_by', sa.String(), nullable=False),
    sa.Column('merge_reason', sa.String(), nullable=False),
    sa.Column('winner_bangumi_id', sa.Integer(), nullable=False),
    sa.Column('loser_bangumi_id', sa.Integer(), nullable=False),
    sa.Column('loser_snapshot', sa.Text(), nullable=False),
    sa.Column('moved_torrent_ids', sa.Text(), nullable=False),
    sa.Column('dropped_torrents', sa.Text(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('undone_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['loser_bangumi_id'], ['bangumi.id'], name=op.f('fk_bangumi_merge_history_loser_bangumi_id_bangumi')),
    sa.ForeignKeyConstraint(['winner_bangumi_id'], ['bangumi.id'], name=op.f('fk_bangumi_merge_history_winner_bangumi_id_bangumi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bangumi_merge_history'))
    )
    with op.batch_alter_table('bangumi_merge_history', schema=None) as batch_op:
        batch_op.create_index('ix_bangumi_merge_history_loser', ['loser_bangumi_id'], unique=False)
        batch_op.create_index('ix_bangumi_merge_history_winner', ['winner_bangumi_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangumi_merge_history', schema=None) as batch_op:
        batch_op.drop_index('ix_bangumi_merge_history_winner')
        batch_op.drop_index('ix_bangumi_merge_history_loser')

    op.drop_table('bangumi_merge_history')
    # ### end Alembic commands ###
